services:
  aphw-ddi-police-force:
    build:
      context: .
      target: production
    image: aphw-ddi-police-force
    container_name: aphw-ddi-police-force
    environment:
      APPINSIGHTS_CLOUDROLE: aphw-ddi-police-force-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
