# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  aphw-ddi-police-force:
    build:
      target: development
    image: aphw-ddi-police-force-development
    container_name: aphw-ddi-police-force-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
