# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  aphw-ddi-police-force:
    build:
      target: development
    image: aphw-ddi-police-force-development
    container_name: aphw-ddi-police-force-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      APPINSIGHTS_CLOUDROLE: aphw-ddi-police-force-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://aphw-ddi-police-force-azurite:10000/devstoreaccount1;}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_FORCE_KML_CONTAINER: "police-force-kml"
      AZURE_STORAGE_POSTCODE_COORDS_CONTAINER: "postcode-areas"
    depends_on:
      - aphw-ddi-police-force-azurite
  
  aphw-ddi-police-force-azurite:
    command: "azurite-blob --skipApiVersionCheck --loose --blobHost 0.0.0.0 --blobPort 10005 -l data"
    volumes:
      - azurite_data:/opt/azurite/data
    ports:
      - "10005:10005"

volumes:
  azurite_data:
