# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  aphw-ddi-police-force:
    build:
      target: development
    image: aphw-ddi-police-force-development
    container_name: aphw-ddi-police-force-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    depends_on:
      - aphw-ddi-police-force-azurite

  aphw-ddi-police-force-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0