services:
  aphw-ddi-police-force:
    build:
      context: .
      target: production
    image: aphw-ddi-police-force
    container_name: aphw-ddi-police-force
    depends_on:
      - aphw-ddi-police-force-azurite
    environment:
      APPINSIGHTS_CLOUDROLE: aphw-ddi-police-force-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_CONNECTION_STRING: "UseDevelopmentStorage=true"
      AZURE_STORAGE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_STORAGE_ACCOUNT_NAME:-test}
      AZURE_STORAGE_FORCE_KML_CONTAINER: "aphw-ddi-policeforces"
      AZURE_STORAGE_POSTCODE_COORDS_CONTAINER: "aphw-ddi-postcodeareas"
      OS_PLACES_API_KEY: ${OS_PLACES_API_KEY:-test}
      OS_PLACES_API_BASE_URL: ${OS_PLACES_API_BASE_URL:-test}

  aphw-ddi-police-force-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0
    command: "azurite-blob --skipApiVersionCheck --loose --blobHost 0.0.0.0 --blobPort 10005"