{{- include "ffc-helm-library.container-secret" (list . "aphw-ddi-police-force.container-secret") -}}
{{- define "aphw-ddi-police-force.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.azureStorageConnectionString }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
  OS_PLACES_API_KEY: {{ quote .Values.container.osPlacesApiKey }}
{{- end -}}
