{{- include "ffc-helm-library.container-secret" (list . "aphw-ddi-police-force.container-secret") -}}
{{- define "aphw-ddi-police-force.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
