environment: production
environmentCode:
name: aphw-ddi-police-force
namespace: aphw-ddi
workstream: aphw-ddi
image: aphw-ddi-police-force

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: aphw-ddi-police-force-config-map

containerSecret:
  name: aphw-ddi-police-force-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000
  osPlacesApiKey: dummy
  osPlacesBaseUrl: dummy
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageAccountName: dummy
  policeForceKmlContainer: aphw-ddi-policeforces
  postcodeAreaContainer: aphw-ddi-postcodeareas

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
